#!/usr/bin/env python3
"""Fill Screenshot Buddy + Clipboard Buddy String Catalogs for all supported locales."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
LANGS = ["en", "nl", "pt", "es", "fr", "it", "ar", "zh", "ru", "ja"]

# key -> {lang: value}. English may equal the key.
SCREENSHOT: dict[str, dict[str, str]] = {
    "Gallery": {
        "en": "Gallery",
        "nl": "Galerij",
        "pt": "Galeria",
        "es": "Galería",
        "fr": "Galerie",
        "it": "Galleria",
        "ar": "المعرض",
        "zh": "图库",
        "ru": "Галерея",
        "ja": "ギャラリー",
    },
    "Copy": {
        "en": "Copy",
        "nl": "Kopiëren",
        "pt": "Copiar",
        "es": "Copiar",
        "fr": "Copier",
        "it": "Copia",
        "ar": "نسخ",
        "zh": "复制",
        "ru": "Копировать",
        "ja": "コピー",
    },
    "Paste": {
        "en": "Paste",
        "nl": "Plakken",
        "pt": "Colar",
        "es": "Pegar",
        "fr": "Coller",
        "it": "Incolla",
        "ar": "لصق",
        "zh": "粘贴",
        "ru": "Вставить",
        "ja": "ペースト",
    },
    "New screenshots appear here automatically.": {
        "en": "New screenshots appear here automatically.",
        "nl": "Nieuwe schermafbeeldingen verschijnen hier automatisch.",
        "pt": "Novas capturas aparecem aqui automaticamente.",
        "es": "Las capturas nuevas aparecen aquí automáticamente.",
        "fr": "Les nouvelles captures apparaissent ici automatiquement.",
        "it": "Le nuove schermate compaiono qui automaticamente.",
        "ar": "تظهر لقطات الشاشة الجديدة هنا تلقائيًا.",
        "zh": "新截图会自动出现在这里。",
        "ru": "Новые снимки появляются здесь автоматически.",
        "ja": "新しいスクリーンショットはここに自動で表示されます。",
    },
    "Recent shots": {
        "en": "Recent shots",
        "nl": "Recente shots",
        "pt": "Capturas recentes",
        "es": "Capturas recientes",
        "fr": "Captures récentes",
        "it": "Scatti recenti",
        "ar": "اللقطات الأخيرة",
        "zh": "最近截图",
        "ru": "Недавние снимки",
        "ja": "最近のショット",
    },
    "This cannot be undone.": {
        "en": "This cannot be undone.",
        "nl": "Dit kan niet ongedaan worden gemaakt.",
        "pt": "Isto não pode ser desfeito.",
        "es": "Esto no se puede deshacer.",
        "fr": "Cette action est irréversible.",
        "it": "Questa azione non può essere annullata.",
        "ar": "لا يمكن التراجع عن هذا.",
        "zh": "此操作无法撤销。",
        "ru": "Это действие нельзя отменить.",
        "ja": "この操作は取り消せません。",
    },
    "Blur amount": {
        "en": "Blur amount",
        "nl": "Vervagingssterkte",
        "pt": "Intensidade do desfoque",
        "es": "Cantidad de desenfoque",
        "fr": "Intensité du flou",
        "it": "Intensità sfocatura",
        "ar": "مقدار التمويه",
        "zh": "模糊强度",
        "ru": "Сила размытия",
        "ja": "ぼかしの強さ",
    },
    "Border width": {
        "en": "Border width",
        "nl": "Randdikte",
        "pt": "Espessura da borda",
        "es": "Ancho del borde",
        "fr": "Épaisseur du contour",
        "it": "Spessore bordo",
        "ar": "سمك الحدود",
        "zh": "边框宽度",
        "ru": "Толщина рамки",
        "ja": "枠の太さ",
    },
    "Opacity": {
        "en": "Opacity",
        "nl": "Dekking",
        "pt": "Opacidade",
        "es": "Opacidad",
        "fr": "Opacité",
        "it": "Opacità",
        "ar": "الشفافية",
        "zh": "不透明度",
        "ru": "Непрозрачность",
        "ja": "不透明度",
    },
    "Size": {
        "en": "Size",
        "nl": "Grootte",
        "pt": "Tamanho",
        "es": "Tamaño",
        "fr": "Taille",
        "it": "Dimensione",
        "ar": "الحجم",
        "zh": "大小",
        "ru": "Размер",
        "ja": "サイズ",
    },
    "Stroke size": {
        "en": "Stroke size",
        "nl": "Lijndikte",
        "pt": "Espessura do traço",
        "es": "Grosor del trazo",
        "fr": "Épaisseur du trait",
        "it": "Spessore tratto",
        "ar": "سمك الخط",
        "zh": "描边粗细",
        "ru": "Толщина штриха",
        "ja": "線の太さ",
    },
    "Thickness": {
        "en": "Thickness",
        "nl": "Dikte",
        "pt": "Espessura",
        "es": "Grosor",
        "fr": "Épaisseur",
        "it": "Spessore",
        "ar": "السماكة",
        "zh": "粗细",
        "ru": "Толщина",
        "ja": "太さ",
    },
    "Detected": {
        "en": "Detected",
        "nl": "Gedetecteerd",
        "pt": "Detectado",
        "es": "Detectado",
        "fr": "Détecté",
        "it": "Rilevato",
        "ar": "تم الكشف",
        "zh": "已检测",
        "ru": "Обнаружено",
        "ja": "検出済み",
    },
    "OCR": {
        "en": "OCR",
        "nl": "OCR",
        "pt": "OCR",
        "es": "OCR",
        "fr": "OCR",
        "it": "OCR",
        "ar": "OCR",
        "zh": "OCR",
        "ru": "OCR",
        "ja": "OCR",
    },
    "Click a pixel to copy its hex color.": {
        "en": "Click a pixel to copy its hex color.",
        "nl": "Klik op een pixel om de hex-kleur te kopiëren.",
        "pt": "Clique em um pixel para copiar a cor hex.",
        "es": "Haz clic en un píxel para copiar su color hex.",
        "fr": "Cliquez sur un pixel pour copier sa couleur hex.",
        "it": "Fai clic su un pixel per copiare il colore esadecimale.",
        "ar": "انقر على بكسل لنسخ لونه الست عشري.",
        "zh": "点击像素以复制其十六进制颜色。",
        "ru": "Нажмите на пиксель, чтобы скопировать hex-цвет.",
        "ja": "ピクセルをクリックしてHEXカラーをコピーします。",
    },
    "Click the image to place text, or click existing text to edit.": {
        "en": "Click the image to place text, or click existing text to edit.",
        "nl": "Klik op de afbeelding om tekst te plaatsen, of op bestaande tekst om te bewerken.",
        "pt": "Clique na imagem para colocar texto, ou em texto existente para editar.",
        "es": "Haz clic en la imagen para colocar texto, o en texto existente para editarlo.",
        "fr": "Cliquez sur l’image pour placer du texte, ou sur un texte existant pour le modifier.",
        "it": "Fai clic sull’immagine per inserire testo, o sul testo esistente per modificarlo.",
        "ar": "انقر على الصورة لوضع نص، أو على نص موجود لتحريره.",
        "zh": "点击图像以放置文字，或点击已有文字进行编辑。",
        "ru": "Нажмите на изображение, чтобы добавить текст, или на существующий текст для правки.",
        "ja": "画像をクリックしてテキストを配置するか、既存のテキストをクリックして編集します。",
    },
    "Drag handles to resize, drag inside the box to move, or drag on the image to select an area. Then confirm.": {
        "en": "Drag handles to resize, drag inside the box to move, or drag on the image to select an area. Then confirm.",
        "nl": "Sleep handvatten om te schalen, sleep in het vak om te verplaatsen, of sleep op de afbeelding om een gebied te selecteren. Bevestig daarna.",
        "pt": "Arraste as alças para redimensionar, arraste dentro da caixa para mover, ou arraste na imagem para selecionar uma área. Depois confirme.",
        "es": "Arrastra los controladores para redimensionar, dentro de la caja para mover, o en la imagen para seleccionar un área. Luego confirma.",
        "fr": "Faites glisser les poignées pour redimensionner, l’intérieur pour déplacer, ou sur l’image pour sélectionner. Puis confirmez.",
        "it": "Trascina le maniglie per ridimensionare, l’interno per spostare, o sull’immagine per selezionare un’area. Poi conferma.",
        "ar": "اسحب المقابض لتغيير الحجم، أو داخل المربع للنقل، أو على الصورة لتحديد منطقة. ثم أكّد.",
        "zh": "拖动手柄调整大小，拖动框内移动，或在图像上拖选区域，然后确认。",
        "ru": "Тяните маркеры для размера, внутри рамки — для перемещения, по изображению — для выбора области. Затем подтвердите.",
        "ja": "ハンドルをドラッグしてサイズ変更、枠内で移動、画像上で範囲選択。その後確定します。",
    },
    "No matching sensitive data found": {
        "en": "No matching sensitive data found",
        "nl": "Geen overeenkomende gevoelige gegevens gevonden",
        "pt": "Nenhum dado sensível correspondente encontrado",
        "es": "No se encontraron datos sensibles coincidentes",
        "fr": "Aucune donnée sensible correspondante trouvée",
        "it": "Nessun dato sensibile corrispondente trovato",
        "ar": "لم يتم العثور على بيانات حساسة مطابقة",
        "zh": "未找到匹配的敏感数据",
        "ru": "Подходящие конфиденциальные данные не найдены",
        "ja": "一致する機密データは見つかりませんでした",
    },
    "No readable QR code found. Try a sharper crop with more white margin around the code.": {
        "en": "No readable QR code found. Try a sharper crop with more white margin around the code.",
        "nl": "Geen leesbare QR-code gevonden. Probeer een scherpere uitsnede met meer witte rand rond de code.",
        "pt": "Nenhum QR code legível encontrado. Tente um recorte mais nítido com mais margem branca ao redor do código.",
        "es": "No se encontró un código QR legible. Prueba un recorte más nítido con más margen blanco alrededor.",
        "fr": "Aucun code QR lisible trouvé. Essayez un recadrage plus net avec plus de marge blanche.",
        "it": "Nessun codice QR leggibile trovato. Prova un ritaglio più nitido con più margine bianco.",
        "ar": "لم يتم العثور على رمز QR قابل للقراءة. جرّب قصًا أوضح مع هامش أبيض أكبر حول الرمز.",
        "zh": "未找到可读的二维码。请尝试更清晰的裁剪，并在码周围留出更多白边。",
        "ru": "Читаемый QR-код не найден. Попробуйте более чёткий кадр с большим белым полем вокруг кода.",
        "ja": "読み取れるQRコードがありません。コード周りに余白を多めにしたシャープな切り抜きを試してください。",
    },
    "No text selected.": {
        "en": "No text selected.",
        "nl": "Geen tekst geselecteerd.",
        "pt": "Nenhum texto selecionado.",
        "es": "No hay texto seleccionado.",
        "fr": "Aucun texte sélectionné.",
        "it": "Nessun testo selezionato.",
        "ar": "لم يتم تحديد أي نص.",
        "zh": "未选择文本。",
        "ru": "Текст не выбран.",
        "ja": "テキストが選択されていません。",
    },
    "Same soft blur as the sensitive preview.": {
        "en": "Same soft blur as the sensitive preview.",
        "nl": "Dezelfde zachte vervaging als bij de gevoelige voorvertoning.",
        "pt": "O mesmo desfoque suave da prévia sensível.",
        "es": "El mismo desenfoque suave que la vista previa sensible.",
        "fr": "Le même flou doux que l’aperçu sensible.",
        "it": "La stessa sfocatura morbida dell’anteprima sensibile.",
        "ar": "نفس التمويه الناعم المستخدم في معاينة المحتوى الحساس.",
        "zh": "与敏感预览相同的柔和模糊。",
        "ru": "То же мягкое размытие, что и в скрытом превью.",
        "ja": "機密プレビューと同じ柔らかいぼかしです。",
    },
    "Select text in the image like Preview. Use ⌘C or Copy Text.": {
        "en": "Select text in the image like Preview. Use ⌘C or Copy Text.",
        "nl": "Selecteer tekst in de afbeelding zoals in Voorvertoning. Gebruik ⌘C of Kopieer tekst.",
        "pt": "Selecione texto na imagem como no Visualização. Use ⌘C ou Copiar texto.",
        "es": "Selecciona texto en la imagen como en Vista Previa. Usa ⌘C o Copiar texto.",
        "fr": "Sélectionnez du texte dans l’image comme dans Aperçu. Utilisez ⌘C ou Copier le texte.",
        "it": "Seleziona il testo nell’immagine come in Anteprima. Usa ⌘C o Copia testo.",
        "ar": "حدد النص في الصورة كما في المعاينة. استخدم ⌘C أو نسخ النص.",
        "zh": "像“预览”一样在图像中选择文本。使用 ⌘C 或“复制文本”。",
        "ru": "Выделяйте текст на изображении, как в Просмотре. Используйте ⌘C или «Копировать текст».",
        "ja": "プレビューのように画像内のテキストを選択。⌘C または「テキストをコピー」を使用。",
    },
    "Type in the box. Drag the handle to move. Click outside to confirm.": {
        "en": "Type in the box. Drag the handle to move. Click outside to confirm.",
        "nl": "Typ in het vak. Sleep het handvat om te verplaatsen. Klik buiten om te bevestigen.",
        "pt": "Digite na caixa. Arraste a alça para mover. Clique fora para confirmar.",
        "es": "Escribe en la caja. Arrastra el controlador para mover. Haz clic fuera para confirmar.",
        "fr": "Saisissez dans la zone. Faites glisser la poignée pour déplacer. Cliquez dehors pour confirmer.",
        "it": "Digita nella casella. Trascina la maniglia per spostare. Fai clic fuori per confermare.",
        "ar": "اكتب في المربع. اسحب المقبض للنقل. انقر خارجًا للتأكيد.",
        "zh": "在框中输入。拖动手柄移动。点击外部确认。",
        "ru": "Введите текст в поле. Перетащите маркер для перемещения. Кликните снаружи, чтобы подтвердить.",
        "ja": "枠内に入力。ハンドルで移動。外側をクリックして確定。",
    },
    "Uses the sensitive types from Settings → General.": {
        "en": "Uses the sensitive types from Settings → General.",
        "nl": "Gebruikt de gevoelige types uit Instellingen → Algemeen.",
        "pt": "Usa os tipos sensíveis de Ajustes → Geral.",
        "es": "Usa los tipos sensibles de Ajustes → General.",
        "fr": "Utilise les types sensibles de Réglages → Général.",
        "it": "Usa i tipi sensibili da Impostazioni → Generali.",
        "ar": "يستخدم الأنواع الحساسة من الإعدادات ← عام.",
        "zh": "使用“设置 → 通用”中的敏感类型。",
        "ru": "Использует типы конфиденциальных данных из «Настройки → Основные».",
        "ja": "「設定 → 一般」の機密タイプを使用します。",
    },
    "%@ item%@ ready to blur.": {
        "en": "%1$@ item%2$@ ready to blur.",
        "nl": "%1$@ item%2$@ klaar om te vervagen.",
        "pt": "%1$@ item%2$@ pronto%2$@ para desfocar.",
        "es": "%1$@ elemento%2$@ listo%2$@ para desenfocar.",
        "fr": "%1$@ élément%2$@ prêt%2$@ à flouter.",
        "it": "%1$@ elemento%2$@ pronto%2$@ da sfocare.",
        "ar": "%1$@ عنصر جاهز للتمويه.",
        "zh": "%1$@ 项可模糊。",
        "ru": "%1$@ элемент%2$@ готово к размытию.",
        "ja": "%1$@件をぼかせます。",
    },
    "%@ pt": {
        "en": "%@ pt",
        "nl": "%@ pt",
        "pt": "%@ pt",
        "es": "%@ pt",
        "fr": "%@ pt",
        "it": "%@ pt",
        "ar": "%@ نقطة",
        "zh": "%@ pt",
        "ru": "%@ pt",
        "ja": "%@ pt",
    },
    "%@%%": {
        "en": "%@%%",
        "nl": "%@%%",
        "pt": "%@%%",
        "es": "%@%%",
        "fr": "%@%%",
        "it": "%@%%",
        "ar": "%@٪٪",
        "zh": "%@%%",
        "ru": "%@%%",
        "ja": "%@%%",
    },
    "%@": {
        "en": "%@",
        "nl": "%@",
        "pt": "%@",
        "es": "%@",
        "fr": "%@",
        "it": "%@",
        "ar": "%@",
        "zh": "%@",
        "ru": "%@",
        "ja": "%@",
    },
    # Additional UI strings used by the app
    "Annotate": {
        "en": "Annotate",
        "nl": "Annoteren",
        "pt": "Anotar",
        "es": "Anotar",
        "fr": "Annoter",
        "it": "Annota",
        "ar": "تعليق",
        "zh": "批注",
        "ru": "Разметка",
        "ja": "注釈",
    },
    "Annotate tools": {
        "en": "Annotate tools",
        "nl": "Annotatietools",
        "pt": "Ferramentas de anotação",
        "es": "Herramientas de anotación",
        "fr": "Outils d’annotation",
        "it": "Strumenti di annotazione",
        "ar": "أدوات التعليق",
        "zh": "批注工具",
        "ru": "Инструменты разметки",
        "ja": "注釈ツール",
    },
    "Auto-blur": {
        "en": "Auto-blur",
        "nl": "Auto-vervagen",
        "pt": "Desfoque automático",
        "es": "Desenfoque automático",
        "fr": "Flou auto",
        "it": "Sfocatura automatica",
        "ar": "تمويه تلقائي",
        "zh": "自动模糊",
        "ru": "Авторазмытие",
        "ja": "自動ぼかし",
    },
    "Blur": {
        "en": "Blur",
        "nl": "Vervagen",
        "pt": "Desfocar",
        "es": "Desenfocar",
        "fr": "Flouter",
        "it": "Sfoca",
        "ar": "تمويه",
        "zh": "模糊",
        "ru": "Размыть",
        "ja": "ぼかし",
    },
    "Blur all": {
        "en": "Blur all",
        "nl": "Alles vervagen",
        "pt": "Desfocar tudo",
        "es": "Desenfocar todo",
        "fr": "Tout flouter",
        "it": "Sfoca tutto",
        "ar": "تمويه الكل",
        "zh": "全部模糊",
        "ru": "Размыть всё",
        "ja": "すべてぼかす",
    },
    "Cancel": {
        "en": "Cancel",
        "nl": "Annuleren",
        "pt": "Cancelar",
        "es": "Cancelar",
        "fr": "Annuler",
        "it": "Annulla",
        "ar": "إلغاء",
        "zh": "取消",
        "ru": "Отмена",
        "ja": "キャンセル",
    },
    "Delete": {
        "en": "Delete",
        "nl": "Verwijderen",
        "pt": "Apagar",
        "es": "Eliminar",
        "fr": "Supprimer",
        "it": "Elimina",
        "ar": "حذف",
        "zh": "删除",
        "ru": "Удалить",
        "ja": "削除",
    },
    "Delete…": {
        "en": "Delete…",
        "nl": "Verwijderen…",
        "pt": "Apagar…",
        "es": "Eliminar…",
        "fr": "Supprimer…",
        "it": "Elimina…",
        "ar": "حذف…",
        "zh": "删除…",
        "ru": "Удалить…",
        "ja": "削除…",
    },
    "Delete Screenshot?": {
        "en": "Delete Screenshot?",
        "nl": "Schermafbeelding verwijderen?",
        "pt": "Apagar captura?",
        "es": "¿Eliminar captura?",
        "fr": "Supprimer la capture ?",
        "it": "Eliminare lo screenshot?",
        "ar": "حذف لقطة الشاشة؟",
        "zh": "删除截图？",
        "ru": "Удалить снимок?",
        "ja": "スクリーンショットを削除しますか？",
    },
    "Duplicate": {
        "en": "Duplicate",
        "nl": "Dupliceren",
        "pt": "Duplicar",
        "es": "Duplicar",
        "fr": "Dupliquer",
        "it": "Duplica",
        "ar": "تكرار",
        "zh": "复制副本",
        "ru": "Дублировать",
        "ja": "複製",
    },
    "Copy to Clipboard": {
        "en": "Copy to Clipboard",
        "nl": "Kopiëren naar klembord",
        "pt": "Copiar para a área de transferência",
        "es": "Copiar al portapapeles",
        "fr": "Copier dans le presse-papiers",
        "it": "Copia negli appunti",
        "ar": "نسخ إلى الحافظة",
        "zh": "复制到剪贴板",
        "ru": "Копировать в буфер",
        "ja": "クリップボードにコピー",
    },
    "Copy to clipboard": {
        "en": "Copy to clipboard",
        "nl": "Kopiëren naar klembord",
        "pt": "Copiar para a área de transferência",
        "es": "Copiar al portapapeles",
        "fr": "Copier dans le presse-papiers",
        "it": "Copia negli appunti",
        "ar": "نسخ إلى الحافظة",
        "zh": "复制到剪贴板",
        "ru": "Копировать в буфер",
        "ja": "クリップボードにコピー",
    },
    "Save As": {
        "en": "Save As",
        "nl": "Opslaan als",
        "pt": "Guardar como",
        "es": "Guardar como",
        "fr": "Enregistrer sous",
        "it": "Salva con nome",
        "ar": "حفظ باسم",
        "zh": "另存为",
        "ru": "Сохранить как",
        "ja": "別名で保存",
    },
    "Save As…": {
        "en": "Save As…",
        "nl": "Opslaan als…",
        "pt": "Guardar como…",
        "es": "Guardar como…",
        "fr": "Enregistrer sous…",
        "it": "Salva con nome…",
        "ar": "حفظ باسم…",
        "zh": "另存为…",
        "ru": "Сохранить как…",
        "ja": "別名で保存…",
    },
    "Overwrite": {
        "en": "Overwrite",
        "nl": "Overschrijven",
        "pt": "Substituir",
        "es": "Sobrescribir",
        "fr": "Écraser",
        "it": "Sovrascrivi",
        "ar": "استبدال",
        "zh": "覆盖",
        "ru": "Перезаписать",
        "ja": "上書き",
    },
    "Undo": {
        "en": "Undo",
        "nl": "Ongedaan maken",
        "pt": "Desfazer",
        "es": "Deshacer",
        "fr": "Annuler",
        "it": "Annulla",
        "ar": "تراجع",
        "zh": "撤销",
        "ru": "Отменить",
        "ja": "取り消す",
    },
    "Redo": {
        "en": "Redo",
        "nl": "Opnieuw",
        "pt": "Refazer",
        "es": "Rehacer",
        "fr": "Rétablir",
        "it": "Ripeti",
        "ar": "إعادة",
        "zh": "重做",
        "ru": "Повторить",
        "ja": "やり直す",
    },
    "Smart": {
        "en": "Smart",
        "nl": "Slim",
        "pt": "Inteligente",
        "es": "Inteligente",
        "fr": "Intelligent",
        "it": "Smart",
        "ar": "ذكي",
        "zh": "智能",
        "ru": "Умные",
        "ja": "スマート",
    },
    "QR scan": {
        "en": "QR scan",
        "nl": "QR-scan",
        "pt": "Leitura de QR",
        "es": "Escaneo QR",
        "fr": "Scan QR",
        "it": "Scansione QR",
        "ar": "مسح QR",
        "zh": "扫描二维码",
        "ru": "Скан QR",
        "ja": "QRスキャン",
    },
    "Crop": {
        "en": "Crop",
        "nl": "Bijsnijden",
        "pt": "Recortar",
        "es": "Recortar",
        "fr": "Recadrer",
        "it": "Ritaglia",
        "ar": "قص",
        "zh": "裁剪",
        "ru": "Обрезать",
        "ja": "切り抜き",
    },
    "Text": {
        "en": "Text",
        "nl": "Tekst",
        "pt": "Texto",
        "es": "Texto",
        "fr": "Texte",
        "it": "Testo",
        "ar": "نص",
        "zh": "文字",
        "ru": "Текст",
        "ja": "テキスト",
    },
    "Arrow": {
        "en": "Arrow",
        "nl": "Pijl",
        "pt": "Seta",
        "es": "Flecha",
        "fr": "Flèche",
        "it": "Freccia",
        "ar": "سهم",
        "zh": "箭头",
        "ru": "Стрелка",
        "ja": "矢印",
    },
    "Ellipse": {
        "en": "Ellipse",
        "nl": "Ellips",
        "pt": "Elipse",
        "es": "Elipse",
        "fr": "Ellipse",
        "it": "Ellisse",
        "ar": "قطع ناقص",
        "zh": "椭圆",
        "ru": "Эллипс",
        "ja": "楕円",
    },
    "Rectangle": {
        "en": "Rectangle",
        "nl": "Rechthoek",
        "pt": "Retângulo",
        "es": "Rectángulo",
        "fr": "Rectangle",
        "it": "Rettangolo",
        "ar": "مستطيل",
        "zh": "矩形",
        "ru": "Прямоугольник",
        "ja": "矩形",
    },
    "Free draw": {
        "en": "Free draw",
        "nl": "Vrij tekenen",
        "pt": "Desenho livre",
        "es": "Dibujo libre",
        "fr": "Dessin libre",
        "it": "Disegno libero",
        "ar": "رسم حر",
        "zh": "自由绘制",
        "ru": "Свободное рисование",
        "ja": "フリーハンド",
    },
    "Color picker": {
        "en": "Color picker",
        "nl": "Kleurenkiezer",
        "pt": "Seletor de cores",
        "es": "Selector de color",
        "fr": "Pipette",
        "it": "Contagocce",
        "ar": "منتقي الألوان",
        "zh": "取色器",
        "ru": "Пипетка",
        "ja": "カラーピッカー",
    },
    "Select": {
        "en": "Select",
        "nl": "Selecteren",
        "pt": "Selecionar",
        "es": "Seleccionar",
        "fr": "Sélectionner",
        "it": "Seleziona",
        "ar": "تحديد",
        "zh": "选择",
        "ru": "Выбрать",
        "ja": "選択",
    },
    "Copy Text": {
        "en": "Copy Text",
        "nl": "Tekst kopiëren",
        "pt": "Copiar texto",
        "es": "Copiar texto",
        "fr": "Copier le texte",
        "it": "Copia testo",
        "ar": "نسخ النص",
        "zh": "复制文本",
        "ru": "Копировать текст",
        "ja": "テキストをコピー",
    },
    "Copy all text": {
        "en": "Copy all text",
        "nl": "Alle tekst kopiëren",
        "pt": "Copiar todo o texto",
        "es": "Copiar todo el texto",
        "fr": "Copier tout le texte",
        "it": "Copia tutto il testo",
        "ar": "نسخ كل النص",
        "zh": "复制全部文本",
        "ru": "Копировать весь текст",
        "ja": "すべてのテキストをコピー",
    },
    "Copy selected text": {
        "en": "Copy selected text",
        "nl": "Geselecteerde tekst kopiëren",
        "pt": "Copiar texto selecionado",
        "es": "Copiar texto seleccionado",
        "fr": "Copier le texte sélectionné",
        "it": "Copia testo selezionato",
        "ar": "نسخ النص المحدد",
        "zh": "复制所选文本",
        "ru": "Копировать выбранный текст",
        "ja": "選択したテキストをコピー",
    },
    "Open": {
        "en": "Open",
        "nl": "Openen",
        "pt": "Abrir",
        "es": "Abrir",
        "fr": "Ouvrir",
        "it": "Apri",
        "ar": "فتح",
        "zh": "打开",
        "ru": "Открыть",
        "ja": "開く",
    },
    "Open link": {
        "en": "Open link",
        "nl": "Link openen",
        "pt": "Abrir link",
        "es": "Abrir enlace",
        "fr": "Ouvrir le lien",
        "it": "Apri collegamento",
        "ar": "فتح الرابط",
        "zh": "打开链接",
        "ru": "Открыть ссылку",
        "ja": "リンクを開く",
    },
    "•••• Sensitive": {
        "en": "•••• Sensitive",
        "nl": "•••• Gevoelig",
        "pt": "•••• Sensível",
        "es": "•••• Sensible",
        "fr": "•••• Sensible",
        "it": "•••• Sensibile",
        "ar": "•••• حساس",
        "zh": "•••• 敏感",
        "ru": "•••• Конфиденциально",
        "ja": "•••• 機密",
    },
    "Applies blur to every matching item. Undo with ⌘Z.": {
        "en": "Applies blur to every matching item. Undo with ⌘Z.",
        "nl": "Past vervaging toe op elk overeenkomend item. Ongedaan maken met ⌘Z.",
        "pt": "Aplica desfoque a cada item correspondente. Desfaça com ⌘Z.",
        "es": "Aplica desenfoque a cada elemento coincidente. Deshaz con ⌘Z.",
        "fr": "Applique un flou à chaque élément correspondant. Annulez avec ⌘Z.",
        "it": "Applica la sfocatura a ogni elemento corrispondente. Annulla con ⌘Z.",
        "ar": "يطبق التمويه على كل عنصر مطابق. تراجع بـ ⌘Z.",
        "zh": "对每个匹配项应用模糊。使用 ⌘Z 撤销。",
        "ru": "Размывает каждый совпадающий фрагмент. Отмена — ⌘Z.",
        "ja": "一致する項目すべてにぼかしを適用。⌘Zで取り消し。",
    },
    "Choose types in Settings…": {
        "en": "Choose types in Settings…",
        "nl": "Kies types in Instellingen…",
        "pt": "Escolher tipos em Ajustes…",
        "es": "Elegir tipos en Ajustes…",
        "fr": "Choisir les types dans Réglages…",
        "it": "Scegli i tipi in Impostazioni…",
        "ar": "اختر الأنواع من الإعدادات…",
        "zh": "在设置中选择类型…",
        "ru": "Выберите типы в Настройках…",
        "ja": "設定でタイプを選択…",
    },
    "Confirm crop": {
        "en": "Confirm crop",
        "nl": "Bijsnijden bevestigen",
        "pt": "Confirmar recorte",
        "es": "Confirmar recorte",
        "fr": "Confirmer le recadrage",
        "it": "Conferma ritaglio",
        "ar": "تأكيد القص",
        "zh": "确认裁剪",
        "ru": "Подтвердить обрезку",
        "ja": "切り抜きを確定",
    },
    "Confirm text": {
        "en": "Confirm text",
        "nl": "Tekst bevestigen",
        "pt": "Confirmar texto",
        "es": "Confirmar texto",
        "fr": "Confirmer le texte",
        "it": "Conferma testo",
        "ar": "تأكيد النص",
        "zh": "确认文字",
        "ru": "Подтвердить текст",
        "ja": "テキストを確定",
    },
    "Collapse tools": {
        "en": "Collapse tools",
        "nl": "Tools inklappen",
        "pt": "Recolher ferramentas",
        "es": "Contraer herramientas",
        "fr": "Réduire les outils",
        "it": "Comprimi strumenti",
        "ar": "طي الأدوات",
        "zh": "收起工具",
        "ru": "Свернуть инструменты",
        "ja": "ツールを折りたたむ",
    },
}

CLIPBOARD: dict[str, dict[str, str]] = {
    "History": {
        "en": "History",
        "nl": "Geschiedenis",
        "pt": "Histórico",
        "es": "Historial",
        "fr": "Historique",
        "it": "Cronologia",
        "ar": "السجل",
        "zh": "历史记录",
        "ru": "История",
        "ja": "履歴",
    },
    "Favorites": {
        "en": "Favorites",
        "nl": "Favorieten",
        "pt": "Favoritos",
        "es": "Favoritos",
        "fr": "Favoris",
        "it": "Preferiti",
        "ar": "المفضلة",
        "zh": "收藏",
        "ru": "Избранное",
        "ja": "お気に入り",
    },
    "Recent": {
        "en": "Recent",
        "nl": "Recent",
        "pt": "Recentes",
        "es": "Recientes",
        "fr": "Récent",
        "it": "Recenti",
        "ar": "الأخيرة",
        "zh": "最近",
        "ru": "Недавние",
        "ja": "最近",
    },
    "Files": {
        "en": "Files",
        "nl": "Bestanden",
        "pt": "Arquivos",
        "es": "Archivos",
        "fr": "Fichiers",
        "it": "File",
        "ar": "الملفات",
        "zh": "文件",
        "ru": "Файлы",
        "ja": "ファイル",
    },
    "Select an item": {
        "en": "Select an item",
        "nl": "Selecteer een item",
        "pt": "Selecione um item",
        "es": "Selecciona un elemento",
        "fr": "Sélectionnez un élément",
        "it": "Seleziona un elemento",
        "ar": "حدد عنصرًا",
        "zh": "选择一个项目",
        "ru": "Выберите элемент",
        "ja": "項目を選択",
    },
    "No favorites yet": {
        "en": "No favorites yet",
        "nl": "Nog geen favorieten",
        "pt": "Ainda sem favoritos",
        "es": "Aún no hay favoritos",
        "fr": "Pas encore de favoris",
        "it": "Nessun preferito ancora",
        "ar": "لا مفضلات بعد",
        "zh": "还没有收藏",
        "ru": "Пока нет избранного",
        "ja": "お気に入りはまだありません",
    },
    "Copied to clipboard": {
        "en": "Copied to clipboard",
        "nl": "Gekopieerd naar klembord",
        "pt": "Copiado para a área de transferência",
        "es": "Copiado al portapapeles",
        "fr": "Copié dans le presse-papiers",
        "it": "Copiato negli appunti",
        "ar": "تم النسخ إلى الحافظة",
        "zh": "已复制到剪贴板",
        "ru": "Скопировано в буфер",
        "ja": "クリップボードにコピーしました",
    },
    "Could not create a QR code for this item.": {
        "en": "Could not create a QR code for this item.",
        "nl": "Kon geen QR-code maken voor dit item.",
        "pt": "Não foi possível criar um QR code para este item.",
        "es": "No se pudo crear un código QR para este elemento.",
        "fr": "Impossible de créer un code QR pour cet élément.",
        "it": "Impossibile creare un codice QR per questo elemento.",
        "ar": "تعذر إنشاء رمز QR لهذا العنصر.",
        "zh": "无法为此项目生成二维码。",
        "ru": "Не удалось создать QR-код для этого элемента.",
        "ja": "この項目のQRコードを作成できませんでした。",
    },
    "%@ pasteboard flavor%@ stored": {
        "en": "%1$@ pasteboard flavor%2$@ stored",
        "nl": "%1$@ klembordtype%2$@ opgeslagen",
        "pt": "%1$@ formato%2$@ da área de transferência armazenado%2$@",
        "es": "%1$@ formato%2$@ del portapapeles guardado%2$@",
        "fr": "%1$@ format%2$@ du presse-papiers enregistré%2$@",
        "it": "%1$@ formato%2$@ degli appunti salvato%2$@",
        "ar": "تم حفظ %1$@ نوع من الحافظة",
        "zh": "已存储 %1$@ 种剪贴板格式",
        "ru": "Сохранено форматов буфера: %1$@",
        "ja": "%1$@件のペーストボード形式を保存",
    },
    "Add to Favorites": {
        "en": "Add to Favorites",
        "nl": "Toevoegen aan favorieten",
        "pt": "Adicionar aos favoritos",
        "es": "Añadir a favoritos",
        "fr": "Ajouter aux favoris",
        "it": "Aggiungi ai preferiti",
        "ar": "إضافة إلى المفضلة",
        "zh": "添加收藏",
        "ru": "В избранное",
        "ja": "お気に入りに追加",
    },
    "Remove from Favorites": {
        "en": "Remove from Favorites",
        "nl": "Verwijderen uit favorieten",
        "pt": "Remover dos favoritos",
        "es": "Quitar de favoritos",
        "fr": "Retirer des favoris",
        "it": "Rimuovi dai preferiti",
        "ar": "إزالة من المفضلة",
        "zh": "取消收藏",
        "ru": "Убрать из избранного",
        "ja": "お気に入りから削除",
    },
    "Copy Image": {
        "en": "Copy Image",
        "nl": "Afbeelding kopiëren",
        "pt": "Copiar imagem",
        "es": "Copiar imagen",
        "fr": "Copier l’image",
        "it": "Copia immagine",
        "ar": "نسخ الصورة",
        "zh": "复制图像",
        "ru": "Копировать изображение",
        "ja": "画像をコピー",
    },
    "Copy to Clipboard": {
        "en": "Copy to Clipboard",
        "nl": "Kopiëren naar klembord",
        "pt": "Copiar para a área de transferência",
        "es": "Copiar al portapapeles",
        "fr": "Copier dans le presse-papiers",
        "it": "Copia negli appunti",
        "ar": "نسخ إلى الحافظة",
        "zh": "复制到剪贴板",
        "ru": "Копировать в буфер",
        "ja": "クリップボードにコピー",
    },
    "Make QR Code": {
        "en": "Make QR Code",
        "nl": "QR-code maken",
        "pt": "Criar código QR",
        "es": "Crear código QR",
        "fr": "Créer un code QR",
        "it": "Crea codice QR",
        "ar": "إنشاء رمز QR",
        "zh": "生成二维码",
        "ru": "Создать QR-код",
        "ja": "QRコードを作成",
    },
    "QR Code": {
        "en": "QR Code",
        "nl": "QR-code",
        "pt": "Código QR",
        "es": "Código QR",
        "fr": "Code QR",
        "it": "Codice QR",
        "ar": "رمز QR",
        "zh": "二维码",
        "ru": "QR-код",
        "ja": "QRコード",
    },
    "Copy": {
        "en": "Copy",
        "nl": "Kopiëren",
        "pt": "Copiar",
        "es": "Copiar",
        "fr": "Copier",
        "it": "Copia",
        "ar": "نسخ",
        "zh": "复制",
        "ru": "Копировать",
        "ja": "コピー",
    },
    "Done": {
        "en": "Done",
        "nl": "Klaar",
        "pt": "Concluído",
        "es": "Listo",
        "fr": "OK",
        "it": "Fine",
        "ar": "تم",
        "zh": "完成",
        "ru": "Готово",
        "ja": "完了",
    },
    "Open Link": {
        "en": "Open Link",
        "nl": "Link openen",
        "pt": "Abrir link",
        "es": "Abrir enlace",
        "fr": "Ouvrir le lien",
        "it": "Apri collegamento",
        "ar": "فتح الرابط",
        "zh": "打开链接",
        "ru": "Открыть ссылку",
        "ja": "リンクを開く",
    },
    "Open link": {
        "en": "Open link",
        "nl": "Link openen",
        "pt": "Abrir link",
        "es": "Abrir enlace",
        "fr": "Ouvrir le lien",
        "it": "Apri collegamento",
        "ar": "فتح الرابط",
        "zh": "打开链接",
        "ru": "Открыть ссылку",
        "ja": "リンクを開く",
    },
    "Search": {
        "en": "Search",
        "nl": "Zoeken",
        "pt": "Pesquisar",
        "es": "Buscar",
        "fr": "Rechercher",
        "it": "Cerca",
        "ar": "بحث",
        "zh": "搜索",
        "ru": "Поиск",
        "ja": "検索",
    },
}


def apply(path: Path, translations: dict[str, dict[str, str]]) -> int:
    data = json.loads(path.read_text(encoding="utf-8"))
    strings = data.setdefault("strings", {})
    updated = 0
    for key, locs in translations.items():
        entry = strings.setdefault(key, {})
        localizations = entry.setdefault("localizations", {})
        for lang in LANGS:
            value = locs.get(lang)
            if value is None:
                continue
            current = localizations.get(lang, {}).get("stringUnit", {}).get("value")
            if current == value and localizations.get(lang, {}).get("stringUnit", {}).get("state") == "translated":
                continue
            localizations[lang] = {
                "stringUnit": {
                    "state": "translated",
                    "value": value,
                }
            }
            updated += 1
        # Drop empty stub entries that only had no localizations
        if "extractionState" not in entry and localizations:
            pass
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return updated


def main() -> None:
    shot = ROOT / "screenshot-buddy/ScreenshotBuddy/Resources/Localizable.xcstrings"
    clip = ROOT / "clipboard-buddy/ClipboardBuddy/Resources/Localizable.xcstrings"
    n1 = apply(shot, SCREENSHOT)
    n2 = apply(clip, CLIPBOARD)
    print(f"Screenshot Buddy: wrote {n1} localization units → {shot}")
    print(f"Clipboard Buddy: wrote {n2} localization units → {clip}")


if __name__ == "__main__":
    main()
